In [371]:
# from sklearn import svm,metrics
# from sklearn.neighbors import KNeighborsClassifier # 븐류
# from sklearn.neighbors import KNeighborsRegressor # 회귀- 예측
from sklearn.linear_model import LinearRegression # 선형회귀
from sklearn.preprocessing import PolynomialFeatures # 다항특성을 만들어주는 라이브러리
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
import random
import matplotlib.pyplot as plt
import matplotlib
import glob, os.path, re

matplotlib.rcParams['axes.unicode_minus'] = False  # 마이너스 표시 해결
# 한글설정
matplotlib.rcParams['font.family'] = 'Malgun Gothic' # windows 사용자
# matplotlib.rcParams['font.family'] = 'AppleGothic Gothic' # Mac사용자
matplotlib.rcParams['font.size'] = '10' # 글자크기

In [372]:
import pandas as pd
df = pd.read_csv('https://bit.ly/fish_csv')
df.head()

Species  Weight  Length  Diagonal   Height   Width
0   Bream   242.0    25.4      30.0  11.5200  4.0200
1   Bream   290.0    26.3      31.2  12.4800  4.3056
2   Bream   340.0    26.5      31.1  12.3778  4.6961
3   Bream   363.0    29.0      33.5  12.7300  4.4555
4   Bream   430.0    29.0      34.0  12.4440  5.1340

In [373]:
df.iloc[:,1:]

Weight  Length  Diagonal   Height   Width
0     242.0    25.4      30.0  11.5200  4.0200
1     290.0    26.3      31.2  12.4800  4.3056
2     340.0    26.5      31.1  12.3778  4.6961
3     363.0    29.0      33.5  12.7300  4.4555
4     430.0    29.0      34.0  12.4440  5.1340
..      ...     ...       ...      ...     ...
154    12.2    12.2      13.4   2.0904  1.3936
155    13.4    12.4      13.5   2.4300  1.2690
156    12.2    13.0      13.8   2.2770  1.2558
157    19.7    14.3      15.2   2.8728  2.0672
158    19.9    15.0      16.2   2.9322  1.8792

[159 rows x 5 columns]

In [374]:
df['Species']

0      Bream
1      Bream
2      Bream
3      Bream
4      Bream
       ...  
154    Smelt
155    Smelt
156    Smelt
157    Smelt
158    Smelt
Name: Species, Length: 159, dtype: object

In [375]:
# 데이터 확인 : nan, 0, type, 최소값, 최대값, 값의 분포,각 특성별 데이터 최대값 standard scaler
# 1. 데이터 전처리 - data,target 분리
fish_input = df.iloc[:,1:].to_numpy()
fish_target = df['Species'].to_numpy()

# train,test 세트 분리
train_input, test_input, train_target, test_target = train_test_split(
     fish_input,fish_target
)
# 표준화 작업
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
ss.fit(train_input, train_target)
train_scaled = ss.transform(train_input)
test_scaled = ss.transform(test_input)




In [376]:
# 2. 데이터 훈련시키기 - 로지스틱 회귀로
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(train_input, train_target)


c:\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [377]:
# 3. 데이터 예측
predict = lr.predict(train_scaled[:5])
print(predict)



['Pike' 'Pike' 'Pike' 'Pike' 'Pike']


In [378]:
# 4. 데이터 정답률 - train,test
print(lr.score(train_scaled,train_target))
print(lr.score(test_scaled,test_target))


0.3949579831932773
0.225


# 결과값 도출 형태 분석

In [379]:
predict = lr.predict(train_scaled[:5])
print(predict)

['Pike' 'Pike' 'Pike' 'Pike' 'Pike']


In [380]:
lr.classes_

array(['Bream', 'Parkki', 'Perch', 'Pike', 'Roach', 'Smelt', 'Whitefish'],
      dtype=object)

In [381]:
from sklearn.linear_model import LogisticRegression
# max_iter : 반복횟수, 기본설정 : 100
# C 규제 : 올라가면 규제가 약해지고, 낮아지면 규제가 강해짐. 선형회귀 규제 : alpha값으로 지정
lr = LogisticRegression(C=20, max_iter=1000)
lr.fit(train_input, train_target)

c:\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(C=20, max_iter=1000)

In [382]:
proba = lr.predict_proba(train_scaled[:5])
np.round(proba,decimals=3)

array([[0.   , 0.   , 0.008, 0.154, 0.   , 0.837, 0.   ],
       [0.   , 0.   , 0.014, 0.149, 0.   , 0.836, 0.001],
       [0.   , 0.   , 0.   , 0.272, 0.   , 0.728, 0.   ],
       [0.   , 0.   , 0.008, 0.173, 0.   , 0.818, 0.   ],
       [0.001, 0.001, 0.009, 0.162, 0.   , 0.825, 0.001]])

In [383]:
decision = lr.decision_function(test_scaled[:5])
print(np.round(decision,decimals=2))

# 기울기, y절편의 값을 적용시켜서 z 점수 출력
# softMax 함수를 적용해서 가장 높은 확률을 채택해서 결정

[[-1.14  3.54  5.86 -7.11  1.19 -4.38  2.04]
 [-2.62 -2.64  1.02  3.78 -2.91  5.4  -2.03]
 [-2.49 -3.46 -0.08  5.71 -3.83  6.91 -2.76]
 [-4.74 -3.82  2.28  4.49 -3.14  7.4  -2.47]
 [-2.7  -3.16  0.49  4.94 -3.49  6.41 -2.48]]


In [384]:
from scipy.special import softmax
proba = softmax(decision,axis =1)
print(np.round(proba,decimals=3))
print(0.157 +0.128 +0.108 +0.205 +0.118 +0.037 +0.246)

[[0.001 0.087 0.884 0.    0.008 0.    0.019]
 [0.    0.    0.01  0.163 0.    0.825 0.   ]
 [0.    0.    0.001 0.233 0.    0.766 0.   ]
 [0.    0.    0.006 0.051 0.    0.943 0.   ]
 [0.    0.    0.002 0.186 0.    0.811 0.   ]]
0.999


In [386]:
print(lr.score(train_scaled,train_target))
print(lr.score(test_scaled,test_target))

0.2689075630252101
0.175


In [388]:
lr.predict(test_scaled[:5])

array(['Perch', 'Smelt', 'Smelt', 'Smelt', 'Smelt'], dtype=object)

In [389]:
proba = lr.predict_proba(test_scaled[:5])
print(np.round(proba,decimals=3))

[[0.001 0.087 0.884 0.    0.008 0.    0.019]
 [0.    0.    0.01  0.163 0.    0.825 0.   ]
 [0.    0.    0.001 0.233 0.    0.766 0.   ]
 [0.    0.    0.006 0.051 0.    0.943 0.   ]
 [0.    0.    0.002 0.186 0.    0.811 0.   ]]
